language: android
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.gradle"
android:
  components:
  - build-tools-22.0.0
  - android-22
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
before_script: "./gradlew assemble"
script: "./gradlew check"
after_success: "./release.sh"
env:
  global:
  - secure: Q0AJ+GOKKt4HIcFQVPaL5cx2af6uf3s/S0qQpBCAqrjAlXHRqD5lTG4q4YfPVAntlTlrHy7w6Fl8u0ahLKmXUn5V1VbB+ah0wgST2QFmPruCyz5ya1pbOaHoGG6A2ISaaem8P17i6m9cI2P3r57l8KKpAHLTPOSZZn/q9kbgREY42yDiRJDQASbr3Fmckmuqqm4C58VyGDA36IIfS2RMO60gHo+EH+jT5ExTOpVMMwhVWiGqzE3bPmqGZ3+HIqfDRZuFTNiRyoPs4GuiHBoj9A134TUxGSAkDVeoaYnYuirz3F9pDpG0p7v90UDcCq185yNyLf15I+hZthTJ54cvLpo9MM2NFCxi6lw5S8vUWZbRrEiy5Kztuvm9LQYWt/SYKoOr9FwV9/vxKttTR0z7rvWdevhgczkKbAyGTx/qbyjKOC0ov0DA1YbD0a39aPNGbWxcQcrxzAtrJqBVRHzGNCHygKrboSLUaenFSyrcZA44MK4dJp/dWQxc5Fv8vmhG0Xip1LFs3Atz1bz5SdyqZg6lcBv3BjYi7Nz8EYT57uKS26fQIc9dBiVeG+Q91dF3EAmZ/uVQAK/XqXBmY9dj3c+Cw27sAOzdn67FnaFfp15laIH7TTbK2IMEedlji+t2CfJu524XD4BbvJBRPjFo6vaDeqTxvJrWLuhYAXa8wqY=
  - secure: pUfNNhRj1uxpTkJfgjos6e7U7hz6lQH1i2Ev8ld3C6pLntbuBW1/D7VXfDz19YbsTpGWn/PtbhKkUUIhp0cJdw+6YbpxDr21OjC/0DuCQXD4GtCaUqt3wGu+7qsHqQxUy0/M5GDrEtNh3p+ZqawpBXfF1l8xdmeDBSnC5qXX4WgUQnpgbRlIlCEbvDC8iopHS9sygztliHE2rKeAKOR8lyD3UoWxgEb8/3ndEA9AS7fVq1Nnh1UIqckQHn+MMJng/1+wl0e7PKLY9axqs7pz3cRgcz3kI1XwgWThbBKWW5mn1UWR4ZrW428hcwp6h8aLiP6m8XDtnDLKW8YcPb2afhJzRqzJw1X2mI/YIwmq7iJp9nnE7enf/mQp9216U3GHROhNu6hnlVSQ0zheI8WiY/PM2eWMzhZWi7zzE1CoZQ/ERXJ3ii2dtPbHFQWntadHxdKxUhQbTTs3gan1AVsZLRzrq+oIdnttfXIwo0kv8XHrXa5qTgGdhfsXDco5JMMLSb8UIVe0yOxWuNEkCZSDFr+gjFFW+RLM5NtUjLdEyqFXS1qhByhrr4DEzWe6GXaG6wdGCc/nZowZHwfLLwOzJuIyqyFORiPxFwC8xgwO8+KqoX5qPrn4MqYHEqPybTzaoSkn7UM1Z6uqA4J1FhNfZiO48cTyiOFf0i8yCh2dddo=
  - secure: tegeHvZKO967FK82J39V3JhdPoReHZiTd1IlDiK5TmJ0wwNQk+hoBeqPCMW1cOH1dxVH8QHvs2zHf9zvkeYv46h/q2aTVSA9djBO/txjvuR97ra9dH6IBDE678higXLqxB2iSq9TzO+vR2aAnqAkLuGnz87m0bLM78xM0DGFjMS6Ce6gkSPw4vtjgFKd0FfwR2sMeSttf3z3hs8b+mZ13p4us7UtFV0F0Icqs1tUEhTgCS5GJJ1DFLcLuiD6UFIOyOGqpjhtDqiOJ/1vyKORIPJnInQixebnGxbDCS0TzaMdD8S8hiw8FKxpa5VJPjQ82+/2IVuSf/2yF5abNEgc40fAvbTXNq4Iet3zIAKmLfTzvjMjfbxt+D017hjrD4hOxX8j2LcXKMKJ6Kdz5KoePnkwVQv938ESLnHjiNJ+HX1RvSFHFIu397RNRPNP/fpBSvWwIk1VjIiYEfFoueznlt3SunLXr++5AaSUgQNHS8+q8wEmk+k9Yc1rnbtpBnH23553EtS0qORmTnhTNxBPuqCK1Ck6q2xZzGpbIg4pFUAM08PgTrkKzk9tAL+RaltxAXuXnTl+8XoA1rPLOxm5Vm2dg6aL1TRJDllZaotM2WjNC+FqjTc+fDzD1chSj/Luu+vp0q78+ante7pRNHj9vjUN0kQ0aCv64NrEPu3rXfk=
